### ISSUE TITLE
NullPointerException in JarFileInfo

### ISSUE THREAD

**Issue by wimdeblauwe** [AdamBien/xplr#1]
I just tried xplr on a Spring Boot created jar and I get this NPE:

```
Wims-MacBook-Pro:Downloads wdb$ java -jar xplr.jar ~/Projects/my-project/project-server/target/project-server-1.1.1.jar
Exception in thread "main" java.lang.NullPointerException
    at com.airhacks.xplr.JarFileInfo.getManifest(JarFileInfo.java:28)
    at com.airhacks.xplr.JarFileInfo.toString(JarFileInfo.java:110)
    at xplr.Explorer.lambda$toString$2(Explorer.java:45)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at xplr.Explorer.toString(Explorer.java:46)
    at xplr.Explorer.lambda$main$0(Explorer.java:29)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at xplr.Explorer.main(Explorer.java:30)
```

**Comment by ErwanLeroux** [comment]
The problem seems to be in java.util.JarInputStream : http://stackoverflow.com/questions/13814891/jarinputstream-getmanifest-is-null
